# Zsh colors generated by matugen - source in .zshrc
# Note: matugen .hex already includes # prefix

# Primary colors
export COLOR_PRIMARY="{{colors.primary.default.hex}}"
export COLOR_ON_PRIMARY="{{colors.on_primary.default.hex}}"

# Surface colors
export COLOR_SURFACE="{{colors.surface.default.hex}}"
export COLOR_ON_SURFACE="{{colors.on_surface.default.hex}}"
export COLOR_SURFACE_CONTAINER="{{colors.surface_container.default.hex}}"

# Secondary colors
export COLOR_SECONDARY="{{colors.secondary.default.hex}}"
export COLOR_ON_SECONDARY="{{colors.on_secondary.default.hex}}"

# Tertiary colors
export COLOR_TERTIARY="{{colors.tertiary.default.hex}}"
export COLOR_ON_TERTIARY="{{colors.on_tertiary.default.hex}}"

# Outline
export COLOR_OUTLINE="{{colors.outline.default.hex}}"

# Background
export COLOR_BACKGROUND="{{colors.background.default.hex}}"
