preload = /home/omarnix/Pictures/wallpapers/404-page_not_found.png
wallpaper = DP-1,/home/omarnix/Pictures/wallpapers/404-page_not_found.png
wallpaper = eDP-1,/home/omarnix/Pictures/wallpapers/404-page_not_found.png
