source = ~/.cache/wal/colors-hyprlock.conf

general {
  hide_cursor = false
}

grace = 5
no_fade_in = false

animations {
  enabled = true
  bezier = linear, 1, 1, 0, 0
  animation = fadeIn, 1, 5, linear
  animation = fadeOut, 1, 5, linear
  animation = inputFieldDots, 1, 2, linear
}

background {
  monitor =
  path = screenshot
  blur_passes = 4
  blur_size = 8
  noise = 0.01
  contrast = 0.9
  brightness = 0.8
  vibrancy = 0.2
  vibrancy_darkness = 0.0
}

input-field {
  monitor =
  size = 25%, 6%
  outline_thickness = 2
  dots_size = 0.2
  dots_spacing = 0.5
  dots_center = true
  inner_color = rgba(0, 0, 0, 0.0)
  outer_color = $c4
  check_color = $c2
  fail_color = $c1
  font_color = $fg
  fade_on_empty = true
  rounding = 12
  font_family = JetBrainsMono Nerd Font
  placeholder_text = <i>Password...</i>
  fail_text = <b>$PAMFAIL</b>
  hide_input = false
  position = 0, -100
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo -e "<span size='x-large'>$(date +'%I:%M %p')</span>\n<span size='small'><i>$(date +'%A, %B %d')</i></span>"
  color = $fg
  font_size = 28
  font_family = JetBrainsMono Nerd Font
  position = 0, 60
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] /home/omarcash/.local/bin/kb-layout
  color = $c8
  font_size = 12
  font_family = JetBrainsMono Nerd Font
  position = 0, -160
  halign = center
  valign = center
}

label {
  monitor =
  text = Welcome back, $USER
  color = $c4
  font_size = 14
  font_family = JetBrainsMono Nerd Font
  position = 0, -180
  halign = center
  valign = center
}
