# Shell variables
# Generated by 'wal'
wallpaper='/home/omarcash/Pictures/wallpapers/Pastel-Window.png'

# Special
background='#121112'
foreground='#c3c6c7'
cursor='#c3c6c7'

# Colors
color0='#121112'
color1='#4F626A'
color2='#AD5E4A'
color3='#EB9B77'
color4='#597984'
color5='#837E81'
color6='#6D8C93'
color7='#c3c6c7'
color8='#888a8b'
color9='#4F626A'
color10='#AD5E4A'
color11='#EB9B77'
color12='#597984'
color13='#837E81'
color14='#6D8C93'
color15='#c3c6c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
