--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/omarcash/Pictures/wallpapers/Pastel-Window.png"

-- Special
background="#121112"
foreground="#c3c6c7"
cursor="#c3c6c7"

-- Colors
color0="#121112"
color1="#4F626A"
color2="#AD5E4A"
color3="#EB9B77"
color4="#597984"
color5="#837E81"
color6="#6D8C93"
color7="#c3c6c7"
color8="#888a8b"
color9="#4F626A"
color10="#AD5E4A"
color11="#EB9B77"
color12="#597984"
color13="#837E81"
color14="#6D8C93"
color15="#c3c6c7"
