[general]
bars = 14
bar_delimiter = 0

[input]
method = pulse
source = auto

[output]
channels = mono
mono_option = average
autosens = 1
sensitivity = 100
method = raw
data_format = ascii
bar_delimiter = 0

[smoothing]
noise_reduction = 0.77
