#!/usr/bin/env bash
# Show current keyboard layout
hyprctl devices -j | python3 -c "
import json, sys
data = json.load(sys.stdin)
for k in data.get('keyboards', []):
    if 'translated' in k.get('name', ''):
        km = k.get('active_keymap', '')
        if 'US' in km:
            print('US')
        else:
            print(km)
        break
"
